name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: scrape legislature reports
      run: |
        cd wv-legislature
        python agency_reports.py
   - name: Commit any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add wv-legislature
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
